import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import ReactQueryWrapper from "../components/shared/ReactQueryWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body>
        <ReactQueryWrapper>{children}</ReactQueryWrapper>
        <Toaster />
      </body>
    </html>
  );
}
