openapi: 3.0.2
info:
  version: 1.0.0
  title: APMS 3.0 API Docs
  description: >
    This is the documentation for APMS 3.0 Backend API
tags:
  - name: User
    description: Operations about user
servers:
  - url: 'http://localhost:9001/api/'
paths:
  '/users/login':
    $ref: 'paths/users/login.yaml'
  '/users/refresh-token':
    $ref: 'paths/users/refreshToken.yaml'
